name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Start server
      run: npm start &
      env:
       CI: true

    - name: Wait for server to be up
      run: |
        echo "Waiting for server to be up..."
        while ! curl --output /dev/null --silent --head --fail http://localhost:3000; do
          printf '.'
          sleep 5
        done
      env:
        CI: true

    - name: Run Percy with Cypress
      run: npm run test:percy
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
